pyms:
  services:
    swagger:
        path: "swagger"
        file: "swagger.yml"
        url: "/swagger/"
        project_dir: "project"

  config:
    APP_NAME: "tasa_service"
    APP_VERSION: "1.0"
    APPLICATION_ROOT : "/tasa_service"
    CONNECTIONS_STRINGS:
      MYSQL_CONNECTION: "mysql,pymysql,root:ensnare-Series9-Oversleep-bays-0Trudge-payment@mysql:3306/tasa_v2"
    DEBUG: true
    SECRET_KEY: "gjr39dkjn344_!67#"
    TESTING: true
    SQLALCHEMY_DATABASE_URI: "sqlite:///:memory:"
    SQLALCHEMY_TRACK_MODIFICATIONS: true
    ENTITIES_DEFINITIONS_PATH: "static/entities_definitions.json"
    PRIVATE_KEY: "secret"
    ALGORITHMS: "HS256"
    KEY_PRIVATE: "ZmDfcTF7_60GrrY167zsiPd67pEvs0aGOv2oasOM1Pg="