from flask import Flask
from flask import request, session, redirect, url_for

import funcs
import connection
import user


app = Flask(__name__, static_url_path="", static_folder="../frontend")
app.secret_key= b'#$somestrangesupersecrethashautogenerated!/___'

@app.route('/ping', methods=['GET', 'POST'])
def ping():
    return 'Hello, World!'

@app.route('/')
def index():
    if 'user' in session:
        return "Welcome: "+ session["user"]
    return "<script> location.href=\'/index.html\' </script>"

@app.route('/saveUser', methods=['POST'])
def saveUser():
    is_logged = funcs.validateSession(session)
    if is_logged == -1:
        return "<script> location.href=\'/index.html\' </script>"
    dict_form = funcs.parseForm(request.form, funcs.saveUser)
    if dict_form == -1:
        return "Sorry The User Already exists."
    return dict_form


@app.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == "GET":
        return "<script> location.href=\'/index.html\' </script>"
    else:
        dict_form = funcs.parseForm(request.form, funcs.searchUser)
        if dict_form != -1:
            session['user'] = dict_form["email"]
            return redirect(url_for('index'))

        return '<script> alert("You are not enable in the login, please contact the administrator"); location.href=\'/index.html\' </script>'

