version: "2.2"

services:
  # We are using these 2 containers because automatic TLS certs from docker registry don't work
  # Estamos usando estos 2 contenedores porque los certs automaticos con docker registry no funcionan
  # https://github.com/docker/distribution/issues/2545

  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - /etc/nginx/vhost.d
  #     - /usr/share/nginx/html
  #     - ./certs:/etc/nginx/certs:ro
  #     - ./nginx-custom.conf:/etc/nginx/conf.d/custom.conf:ro
  #   labels:
  #     - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  # letsencrypt:
  #   image: jrcs/letsencrypt-nginx-proxy-companion
  #   restart: always
  #   volumes:
  #     - ./certs:/etc/nginx/certs:rw
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   volumes_from:
  #     - nginx-proxy:rw
  
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ensnare-Series9-Oversleep-bays-0Trudge-payment
    volumes:
      - /data/mysql:/var/lib/mysql
    expose:
      - "3606"
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  proxy:
    image: nginx
    expose:
      - "80"
    environment:
      VIRTUAL_HOST: docker.juansebestia.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: docker.juansebestia.com
      LETSENCRYPT_EMAIL: juanse.cloud@gmail.com
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
    # depends_on:
    #   - frontend
    #   - back
    #   - nginx-proxy
    # links:
    #   - frontend
    #   - back
    restart: always
  