version: "2.2"

services:
  
  mysql:
    image: mysql
    command: ["mysqld", "--mysql-native-password=ON"]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - /data/mysql:/var/lib/mysql
    expose:
      - "3306"
    ports:
        - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # BACK
  tasa_ms:
    image: us-central1-docker.pkg.dev/tasa-dev-01/tasa/tasa_ms:latest
    container_name: tasa_ms
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_PORT: 3606
      DATABASE_NAME: $DATABASE_NAME
    volumes:
      - /data/tasa_ms:/app/project/images
    expose:
      - "5024"
    ports:
      - "5024:5024"
    restart: always

  stream_ms:
    image: us-central1-docker.pkg.dev/tasa-dev-01/tasa/stream_ms:latest
    container_name: stream_ms
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_PORT: 3606
      DATABASE_NAME: $DATABASE_NAME
    expose:
      - "5024"
    ports:
      - "5025:5024"
    restart: always
  
  # Also contain front files
  proxy:
    image: us-central1-docker.pkg.dev/tasa-dev-01/tasa/proxy:latest
    expose:
      - "80"
    ports:
      - "8082:80"
    restart: always
    volumes:
      - ./proxy-dev.conf:/etc/nginx/conf.d/default.conf:ro
  
  # JOBS
  back-migration:
    image: flyway/flyway
    command: "-locations=\"filesystem:/flyway/sql\" -url=jdbc:mysql://mysql/ -schemas=$DATABASE_NAME -user=$MYSQL_USER -password=$MYSQL_PASSWORD -connectRetries=60 migrate"
    volumes:
      - ../../back/migrations/seeds:/flyway/sql
    depends_on:
      - mysql
