---
  swagger: '2.0'
  info:
    description: This is a microservice in Python about RoceServices
    version: 1.0.0
    title: Roce Service Microservices
  tags:
    - name: Roce
      description: ''
    - name: Grids
      description: Service methods that provide data to build grids on the graphic interface
  schemes:
    - http
  paths:
    /get_notification:
      get:
          tags:
            - "Notification"
          summary: "Notification"
          operationId: "get_notification"
          description: "Roles"
          produces:
            - "application/json"
          parameters:
            - in: "header"
              type: "string"
              name: "Token"
              required: true
          responses:
            '200':
              description: response result successful
              schema:
                type: array
                items:
                  $ref: '#/definitions/notification'                
          x-swagger-router-controller: "project.views.stream"
    /delete_notification:
      delete:
        tags:
          - "Notification"
        summary: "Notification"
        operationId: "delete_notification"
        description: "delete notification"
        produces:
          - "application/json"
        parameters:
          - in: "header"
            required: true
            type: "string"
            name: "Token"
          - in: "query"
            type: "integer"
            name: "id"
            required: false  
        responses:
          '200':
            description: response result successful
        x-swagger-router-controller: "project.views.stream"                                  
  definitions:
        notification:
          type: "object"
          properties:
            Batch:
              type: "string"
            Land_id:
              type: "integer"
            Property_id:
              type: "integer"
  externalDocs:
    description: "Find out more about Swagger"
    url: "http://swagger.io"