pyms:
    services:
      swagger:
        path: ""
        file: "swagger/swagger.yml"
        url: "ws-doc/"
    config:
      DEBUG: true
      TESTING: false
      APP_NAME: "Python Template Microservice"
      APPLICATION_ROOT: /my_Template
	CONNECTIONS_STRINGS:
          POSTGRESQL_MAIN: 	  "postgres,psycopg2,PAP:PRIME@192.168.1.104:5432/DB_PAP_MS"
      DEBUG: true
      SECRET_KEY: "gjr39dkjn344_!67#"
      TESTING: true
      SQLALCHEMY_DATABASE_URI: "sqlite:///:memory:"
      SQLALCHEMY_TRACK_MODIFICATIONS: true
      ENTITIES_DEFINITIONS_PATH: "static/entities_definitions.json"

